### ISSUE TITLE
MySQL/MariaDB support

### ISSUE THREAD

**Issue by boardfish** [ehmicky/autoserver#1]
I'm working on porting an app to autoserver, mostly to investigate how autoserver works and what the eventual benefits of it will be. The app is currently backed by a MySQL/MariaDB database. Could support for MySQL be added?

If I've missed a trick and it's already supported, could it be documented?

**Comment by ehmicky** [comment]
Hi @boardfish,

Thanks for the interest in autoserver! I would advise against using it in production though at the moment. It's currently missing some [key features](https://github.com/ehmicky/autoserver#development-status). 

It's quite a huge project so I expect getting to production-readiness to take at least one year.

At the moment, only MongoDB and an in-memory database are built-in. My goal is to extract the database ORM into its own repository. It was built to add support to other databases, including MySQL. But this is missing at the moment. It's also not probably a good time to add support for it, since the ORM is still unstable and I would like to get it more stable before adding new databases.

However I hope you'll stick around so you can play with it once this project is more stable! Thanks for your interest.
